create table registration_users(id int8 generated by default as identity, username varchar(50) NOT NULL, first_name varchar(50) NOT NULL, last_name varchar(50) DEFAULT NULL,email varchar(50) NOT NULL, primary key (id));






